### ISSUE TITLE
3D Unet error during model export

### ISSUE THREAD

**Issue by karkadad** [openvinotoolkit/nncf#1057]
We’re optimizing the 3D Unet model (https://github.com/CBICA/GaNDLF/blob/master/GANDLF/models/unet.py) using NNCF filter pruning compression algorithm. The filter pruning and finetuning of the model is done successfully, but while exporting the model to ONNX format, we’re running to an issue:
RuntimeError: running_mean should contain 120 elements not 128

This is the stack trace:
` File "/home/envs/gandlf_tests/lib/python3.7/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 141, in wrapped
    retval = module_call(self, *args, **kwargs)
  File "/home/envs/gandlf_tests/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/bduser/dkarkada/GaNDLF_v12/GaNDLF/GANDLF/models/seg_modules/EncodingModule.py", line 69, in forward
    x = self.act(self.in_1(x))
  File "/home/envs/gandlf_tests/lib/python3.7/site-packages/nncf/torch/dynamic_graph/wrappers.py", line 141, in wrapped
    retval = module_call(self, *args, **kwargs)
  File "/home/envs/gandlf_tests/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/envs/gandlf_tests/lib/python3.7/site-packages/torch/nn/modules/instancenorm.py", line 59, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/envs/gandlf_tests/lib/python3.7/site-packages/torch/nn/functional.py", line 2327, in instance_norm
    input, weight, bias, running_mean, running_var, use_input_stats, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 120 elements not 128` 

The finetuning is done using Torch Version: 1.9.0. Any pointers to debug this would be helpful.

**Comment by daniil-lyakhov** [comment]
Hi!
@karkadad, could you please provide more details on how you are exporting the model to ONNX format?

Pruning algorithm working in the following way:
NNCF is wrapping model to enable pruning aware training. The output of pruning algorithm is wrapped model contains all its weights + convolution layers kernel masks with information which layer channel should be pruned and which shouldn't.

To figure out which channels are going to be pruned please refer to pruning algo statistics:
[Example of retrieving statistic from classification sample](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/main.py#L248-L249)
[Docstring on pruning statistics](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/common/pruning/statistics.py#L57-L67)

To actually prune obtained model one should

* Install openvino-dev
For example, to install openvino with onnx prerequirement one should do
```$pip install openvino-dev[onnx]```
* Convert your model to IR format by model optimizer tool using additional parameter `--transform=Pruning`

The simplest way to check your model was pruned is to

compare sizes of .bin parts of original and pruned model
benchmark model performance by [benchmark tool](https://docs.openvino.ai/latest/openvino_inference_engine_tools_benchmark_tool_README.html)
In case something goes wrong and pruning transformation didn't change the size of model please contact me.

To clarify: you can actually remove weights from your model only after openvino model optimizer IR conversion, in the IR format. The api for removing weights directly from torch model was deprecated. You can try to use [this](https://github.com/openvinotoolkit/nncf/blob/2f231aa3903a286dafaa15eaae54758e2a2f346b/nncf/torch/pruning/operations.py#L318-L350), but on your own risks. This functionality isn't tested and updated since a while, and it could be some problems.

If openvino runtime is fitting your requirements I recommend you to try it. It won't only remove weights but should speedup you model overall due to internal optimizations

**Comment by dkurt** [comment]
@karkadad, we faced similar issue with new PyTorch (1.10.0) - seems like there is something changed in InstanceNorm2d.

This is a workaround by @likholat (see https://github.com/likholat/direct/pull/11):

replace
```python
nn.InstanceNorm2d(out_channels)
```
to
```python
InstanceNorm2dONNX(out_channels)
```
where
```python
class InstanceNorm2dFunc(torch.autograd.Function):
    @staticmethod
    def symbolic(g, cls, input):
        return g.op("InstanceNormalization", input, cls.scale, cls.bias)

    @staticmethod
    def forward(self, cls, input):
        y = cls.origin_forward(input)
        return y

class InstanceNorm2dONNX(nn.InstanceNorm2d):
    """
    This is a support class which helps export network with InstanceNorm2d in ONNX format.
    """

    def __init__(self, num_features, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.origin_forward = super().forward
        self.scale = torch.ones(num_features)
        self.bias= torch.zeros(num_features)

    def forward(self, input):
        y = InstanceNorm2dFunc.apply(self, input).clone()
        return y
```

@likholat, please correct if something wrong.

Please note that in our case both scale and bias were initializad by default. Please check if `cls.state_dict()` is empty or not at `forward` in your model.

**Comment by karkadad** [comment]
Using the latest NNCF master branch and with PyTorch version 1.9.0, the export issue is resolved. Hence, closing this ticket.
