### ISSUE TITLE
change bitwidth for a spesicif layer after quantization

### ISSUE THREAD

**Issue by mkimhi** [openvinotoolkit/nncf#1135]
I would like to set a specific bitwidth for a specific layer- post quantization.
Is there a way to set the bitwidth directly? I don't want to copy the weight dict and set a new quantization with config

Thanks

**Comment by ljaljushkin** [comment]
Hello @mkimhi!

There's a [manual initialization of quantization]() for this.

Please refer to the [mobilenet_v2_imagenet_mixed_int_manual.json](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/mixed_precision/mobilenet_v2_imagenet_mixed_int_manual.json#L40) as a reference example.

There are 3 key things:
1) list of bitwidth per operation scopes: 
```json
"compression": {
  "algorithm": "quantization",
  "initializer": {
    "precision": {
      "type": "manual",
        "bitwidth_per_scope": [
          [4, "SqueezeNet/Sequential[classifier]/NNCFConv2d[1]/conv2d_0|WEIGHT"],
          ...
```
You can set an arbitrary bitwidth instead of 4 here. This list is dumped to `bitwidth_per_scope.json` to the log directory for mixed precision (HAWQ) case only: [mobilenet_v2_imagenet_mixed_int_hawq.json](https://github.com/openvinotoolkit/nncf/blob/develop/examples/torch/classification/configs/mixed_precision/mobilenet_v2_imagenet_mixed_int_hawq.json#L32)
If this list is needed even for fully INT8 quantization scenario, we could add an option to dump it for this case as well. Please let us know.
2) target device should be `TRIAL` if you want to set an arbitrary bitwidth. `CPU` device doesn't support INT4 at all, `VPU` one does support INT4, but with [some hardware specific constraints](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/common/hardware/configs/vpu.json#L67) 
```json
"target_device": "TRIAL",
```
3) load pre-trained model and checkpoint via `--weights` option, not a `--resume` one. 
The first option assumes initialization of quantization (bitwidth and quantization ranges), the second - restoring training without any initialization.

It's optional to change other quantization parameters for TRIAL device:
```json
      "algorithm": "quantization",
      "weights": {
            "mode": "asymmetric",
            "per_channel": true,
            "bits": 4
        },
        "activations": {
            "mode": "asymmetric"
        },
```

**Comment by mkimhi** [comment]
Thank you Nikolay,

my desire is to train a network with QAT scheme, and them change a specific layer bit width and fine-tune the model for a little bit more.

thank you

**Comment by ljaljushkin** [comment]
In that case, #1136 can be helpful. `bitwidth_per_scope` is printed to console in debug mode starting from it:
```python
from nncf.common.utils.logger import set_log_level
set_log_level(logging.DEBUG)
```

**Comment by ljaljushkin** [comment]
@mkimhi please let us know whether it helps to achieve your goals and whether we can close the issue

**Comment by mkimhi** [comment]
Thanks again, i figured a solution for my usage

`for name, m in model.named_modules():
    if name== desired_layer:
        m.num_bits = desired_bits
`
am i missing recalculating the scaling when i do that?

**Comment by ljaljushkin** [comment]
@mkimhi, no. quantization scale is staying the same for all bits. No need to recalculate it.
The actual quantization of values takes into account the num_bits and changes the total number of quantized values (e.g. 256 for int8, 16 for int4) and interval between them.

**Comment by mkimhi** [comment]
then for some reason, high_level get the value of 0 when i'm trying to go to extreme low quantization (such as 2 bit or binarization):
![image](https://user-images.githubusercontent.com/42152779/159474210-2a39a201-823c-47f6-b1f7-9f11aef4c44a.png)

**Comment by ljaljushkin** [comment]
@mkimhi sorry for delayed answer
For binarization we use different formula and kernels (DOREFA or XNOR). The mixed precision quantization algorithm doesn't support 1 bit. 
please refer to [docs](https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/Binarization.md), [code](https://github.com/openvinotoolkit/nncf/tree/develop/nncf/torch/binarization) and [configs](https://github.com/openvinotoolkit/nncf/tree/develop/examples/torch/classification/configs/binarization) to learn more about binarization.

**Comment by mkimhi** [comment]
thank you!
