### ISSUE TITLE
About Mixed-Precision Quantization w.r.t. activations

### ISSUE THREAD

**Issue by lixuechenAlfred** [openvinotoolkit/nncf#1189]
Unlike weight quantization, which is based on the computation of average Hessian trace, bit-width setting for activation is implemented naively. Why not use similar Hessian-based algorithm for activation?

**Comment by ljaljushkin** [comment]
Hello @lixuechenAlfred!

Activation can be implemented similarly, as you noticed. The HAWQ paper describes how to do that. 
However, weight and activation precision of the same layer usually should be aligned prior to the execution on the hardware.
That's why independent activation quantization might be not so helpful. But at the same time it can be more general for different hardware.

**Comment by alexsu52** [comment]
Please, reopen the issue if you still have questions.
