### ISSUE TITLE
Can I get models you trained?

### ISSUE THREAD

**Issue by Audrey528** [openvinotoolkit/nncf#1213]
I wanna get classification models or object detection models with fp32 and with int8 you guys trained，can I?

**Comment by wonjuleee** [comment]
You can download the models from https://storage.openvinotoolkit.org/repositories/nncf/models/develop/torch/.
Thank you.

**Comment by wonjuleee** [comment]
Instead of directly inferencing from .pth file, we provide some notebooks for inferencing with OpenVINO IR (convert pth -> onnx -> OpenVINO IR) to compare FP32 and INT8. 
Please refer https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/112-pytorch-post-training-quantization-nncf/112-pytorch-post-training-quantization-nncf.ipynb and https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/113-image-classification-quantization/113-image-classification-quantization.ipynb.

**Comment by Audrey528** [comment]
Thanks for you reply. I use openvinotoolkit/mmdetection to quantization, but the result is worse. I use directly .pth file to inference, while the inference result is the whole picture is full of boxes. At the same time I test the speed, inference speed is slower. So I wanna directly use you guys trained models to test so as to look the effect. I check models from [https://storage.openvinotoolkit.org/repositories/mmdetection/models/](url), but there is only one model, I wanna  get object detection models with fp32 and with int8 you guys trained by  openvinotoolkit/mmdetection. Appreciate it!

**Comment by vshampor** [comment]
Sadly, we do not provide FP32 and INT8 checkpoints for mmdetection models.
