### ISSUE TITLE
Import nncf "directly after torch" required?

### ISSUE THREAD

**Issue by helena-intel** [openvinotoolkit/nncf#1283]
The [PyTorch example](https://github.com/openvinotoolkit/nncf#usage-example-with-pytorch
) in the main README has:
```python
import nncf  # Important - should be imported directly after torch
```

Is it indeed required that nncf is always imported directly after torch (with no other imports in between)? The example imports nncf, but does not use it (which raises an error from linters).

NNCF seems to work fine without the unused import (only `from nncf... import ...`) and with other imports between torch and nncf. For example with code from this PR https://github.com/huggingface/optimum-intel/pull/50/files#diff-fd5a4d0541c4161f72266a67b2ca437a648eaa4ebe9a2909534b7d0353bbc081
Is there a risk of issues doing it that way?

**Comment by alexsu52** [comment]
Hi @helena-intel! Thank you for your question. When you ```import nncf```, NNCF patches PyTorch operations to be able to trace a model. Thus If you don't redefine or explicitly import PyTorch operations in you code between ```import torch``` and ```import nncf``` it will be safe. But I would recommend to ```import nncf``` directly after Torch It allows you to avoid magic errors.

**Comment by helena-intel** [comment]
Thank you! I appreciate the background info. This seems potentially tricky. I think auto-formatters that sort imports are pretty common, so it's easy to accidentally mess this up. If you use a linter it will also warn about an unused nncf import, but relying on the `from nncf import ..` call even later in the import list seems also unwise. Your modified sentence would help for people who know that transformers does this - but in general the advice to import directly after torch seems wise.

Could we also call `patch_torch_operators()` directly, instead of the implicit patching that happens on import? Explicit is maybe better than implicit here?

**Comment by vshampor** [comment]
> Could we also call patch_torch_operators() directly, instead of the implicit patching that happens on import? Explicit is maybe better than implicit here?

NNCF aims to not break regular, non-NNCF-aware operation of the PyTorch framework with the `patch_torch_operators()`, the wrappers that are set up are completely transparent to the end user and do not incur any significant performance overhead in the usual workloads. And, basically, nothing NNCF-related would work reliably for torch if the user forgets to add `patch_torch_operators()`, and to add it indeed before the first usage of NNCF in their code and also before the external torch-dependent package usage. So having explicit `patch_torch_operators()` would only increase complexity, make user unnecessarily aware of the internal NNCF-PyTorch workings, and increase probability of an error due to oversight.

**Comment by helena-intel** [comment]
I love that NNCF is easy to use and that it is only a few lines of code to get a quantized model. But it is very easy to overlook this comment in the example, and when automatically sorting imports, nncf comes before torch. Then it seems you may run into issues that are difficult to debug. I don't think being explicit about what happens ("we're patching pytorch") is necessarily increasing complexity. Having to remember import order is also a form of complexity. It would be good to at least document the import order requirements in the README, so it's not just a note in the example code.
