### ISSUE TITLE
support for yolov5

### ISSUE THREAD

**Issue by liumingzhu6060** [openvinotoolkit/nncf#1325]
is there a tutorial for yolov5 using NNCF PTQ？
when I modify the yolov5 train.py, 'nncf_config = register_default_init_args(nncf_config, dataloader)', 
a problem occured "NotImplementedError: By default it is assumed that the data loader used for initialize produces a tuple/list of (*model_input*, *ground_truth*) and that no special forward arguments have to be set during init. If this is not the case, then instead of your regular data loader you need to pass a specialized version of PTInitializingDataLoader that returns a general (arg
s, kwargs) tuple for your model to be called with at each __next__ call."
Where should I modify  to the yolov5 datasets.py

**Comment by vshampor** [comment]
@liumingzhu6060 this has already been answered here:
https://github.com/openvinotoolkit/nncf/issues/1294

Basically you have to specify for NNCF the format of your dataloader outputs using additional code, because NNCF needs to get data from the dataloader from initialization purposes, but cannot know without additional info just what objects does your dataloader output, i.e. how to unpack them into the `forward` arguments for your model.

**Comment by MaximProshin** [comment]
yolov7 notebook with nncf that might be useful for yolov5 too https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/226-yolov7-optimization
