### ISSUE TITLE
Saving and Loading compressed model in pytorch as pytorch model object

### ISSUE THREAD

**Issue by bijonguha** [openvinotoolkit/nncf#135]
I am facing a issue that when I try to `torch.save(model, model_path)`, it is throwing `TypeError: can't pickle odict_values objects` error. For my project I want to save it as a torch compressed model object and load it for doing prediction on new images. If anyone can help me out here, it would be really great

**Comment by vshampor** [comment]
Greetings, @bijonguha!

Please make sure that this is an NNCF-related issue, not an issue with the model or a pipeline itself, and if it *is* and NNCF-related issue, please post instructions on how to reproduce this.

**Comment by bijonguha** [comment]
Sure. In main.py inside examples/object_detection there is a part in the code where : 

    if config.to_onnx:
        compression_ctrl.export_model(config.to_onnx)
        logger.info("Saved to {}".format(config.to_onnx))
        return

So, here only option is to export the code in onnx format. I was trying to do torch.save(model) but then I was not able to do that and go the issue mentioned in my first comment. TypeError: can't pickle odict_values objects

**Comment by vshampor** [comment]
Greetings, @bijonguha!

Sorry for the late reply.

The `model` that you encounter troubles saving with is `NNCFNetwork`, which wraps the actual compressed model and, along with the trainable parameters and `torch.nn.Module`'s, contains additional attributes, such as ordered dictionaries and such, which are required for NNCF functionality. I think that the PyTorch-recommended way is to save `model.state_dict()` instead of `model`, anyway. Review the sample training pipelines in `examples`, which have the example code saving and loading .pth checkpoints, and comment here if you have further questions.
