### ISSUE TITLE
Exported ONNX-Model is not loadable with OnnxRuntime

### ISSUE THREAD

**Issue by BitCourier** [openvinotoolkit/nncf#1445]
I created a ResNet18 with PyTorch and compressed it with the example code and the config file "resnet18_imagenet_int8_accuracy_aware".

After exporting to .onnx, the file is unable to load in onnxruntime. 
It fails with Error: "[ONNXRuntimeError] : 1 : FAIL : Fatal error: FakeQuantize is not a registered function/op"

Did I do something wrong? Is there a possibility for fixing?

**Comment by ljaljushkin** [comment]
OpenVINO is needed for models with FakeQuantize ops.
There’s an option of quantization algorithm https://github.com/openvinotoolkit/nncf/blob/609a06f4448d81018c106749358f6c53e1d11a22/nncf/config/schemata/algo/quantization.py#L497 to export in another format (Quantize + Dequantize) which should be supported by ONNX Runtime.

**Comment by BitCourier** [comment]
Thank you for your fast reply!
Now I'm stuck with "RuntimeError: PyTorch export to ONNX using QuantizeLinear-DequantizeLinear doesn't support per channel quantization".
I tried setting the  "per_channel" option to false, but this seems to be invalid.

**Comment by ljaljushkin** [comment]
The mentioned error [was removed](https://github.com/openvinotoolkit/nncf/pull/1384/files#diff-938d55043a047f658736abf8d55ca622eff14e4059fcb7692f0fe6846e2ec068L456) on develop branch since per-channel quantization is supported for ONNX opset >= 13:


Suggest using nncf from sources: https://github.com/openvinotoolkit/nncf#installation

**Comment by BitCourier** [comment]
Thank you!
I've now been able to create a .onnx which is loadable with onnxruntime.
