### ISSUE TITLE
NNCF v2.5 increases tensor size and model size raising NPU errors

### ISSUE THREAD

**Issue by dmal-msft** [openvinotoolkit/nncf#1923]
I was using NNCF 2.4 to quantize my model, and it was working great. When I upgraded to 2.5 it seems that the backend was changed, instead of POT it was using another API to run statistics on the calibration data. The model increased in size by 3x, and also it introduced more tensors that are 5D making the inference break on NPU as it doesnt support 5D tensors yet. 

Can you tell me what kind of changes have you introduced in your new backend and how can I mitigate that?
I use the default parameters of the `quantize` function provided. 

Thanks

**Comment by KodiaqQ** [comment]
Thank you for using NNCF, @dmal-msft!

To use the `POT` backend again, you can try this way:

```
import nncf

model = ...
dataset = ...
advanced_parameters = nncf.AdvancedQuantizationParameters(backend_params={"use_pot": True})
quantized_model = nncf.quantize(model, dataset, advanced_parameters=advanced_parameters)
```

**Comment by MaximProshin** [comment]
Dear @dmal-msft

While switching to POT should help you, we plan to remove this option in the future and so we want to investigate your problem. Unfortunately we can't do it without the model. Is it possible to share it (it could be with fake weights) or maybe there is a public analogue which we could look at and see if the problem is reproduced with it?
