### ISSUE TITLE
[Good First Issue][NNCF]: Fixing NNCFGraph export for visualization in Netron

### ISSUE THREAD

**Issue by andrey-churkin** [openvinotoolkit/nncf#2552]
### Context

Neural Network Compression Framework (NNCF) uses an instance of `NNCFGraph` class to represent a framework-specific deep learning model. An instance of `NNCFGraph` class is used in almost every algorithm and serves as the primary means to obtain information about deep learning model.

It is very beneficial to have a way to visualize such graph. One possible way to visualize it is by using a `.dot` file.
Please see `visualize_graph()` method:
https://github.com/openvinotoolkit/nncf/blob/481ce9d9624c4b699878aa337d2e9b78dc25a517/nncf/common/graph/graph.py#L565-L567

The main disadvantage of this approach is that it is very difficult to analyze a `.dot` file for very large models. It is better to use [Netron](https://netron.app/). We already have a method that allows us to export an instance of the `NNCFGraph` class to a format supported by Netron. Actually, we export NNCFGraph to the OpenVINO IR format. Please see [OpenVINO IR format specification](https://docs.openvino.ai/2023.3/openvino_ir.html#openvino-ir-format). We save only the topology (`.XML` file).

Please follow the following code snippet to understand how to save `NNCFGraph` for visualization in Netron

```python
import openvino as ov
from nncf.common.factory import NNCFGraphFactory
from nncf.experimental.common.graph.netron import save_for_netron

ov_model = ov.Core().read_model("<MODEL_PATH>")
graph = NNCFGraphFactory.create(ov_model)
save_for_netron(graph, "graph.xml")
```

### What needs to be done?

- Currently, it is not possible to open the resulting `graph.xml` in Netron. The main task is to resolve this problem by fixing the export. Netron returns the following error: _Error loading OpenVINO model. Unsupported precision 'undefined'_
- Add docstrings for all methods (`get_graph_desc()`, `save_for_netron()`) and classes (`PortDesc`, `NodeDesc`, `EdgeDesc`) inside `nncf.experimental.common.graph.netron` module
- Add tests for the following methods
    - `get_graph_desc()`
    - `PortDesc.as_xml_element()`
    - `NodeDesc.as_xml_element()`
    - `EdgeDesc.as_xml_element()`

### Example Pull Requests

N/A

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)

### Contact points

@andrey-churkin @alexsu52 

### Ticket

N/A

**Comment by DaniAffCH** [comment]
.take

**Comment by DaniAffCH** [comment]
Hi @andrey-churkin,
I dug deeper into the issue and found a potential solution, but I want to discuss the details with you. 

The `dtype` should be retrieved from the instances of the class `NNCFGraphEdge`. However, the class contains only the `nncf dtype` that could be either `FLOAT` or `INTEGER`. This is because the original `ov dtype` is squished into one of these two classes

https://github.com/openvinotoolkit/nncf/blob/481ce9d9624c4b699878aa337d2e9b78dc25a517/nncf/openvino/graph/nncf_graph_builder.py#L32C1-L63C1

The Netron OpenVino frontend supports only the native OpenVino datatypes

https://github.com/lutzroeder/netron/blob/49e3a04a3210cf655e0abb04016e36b2a3bfcebf/source/openvino.js#L748C1-L772C111

So we can choose to save the original data type into the class `NNCFGraphEdge` to display the correct layer dtype in Netron. 

An alternative solution would be to map the `nncf dtype` `FLOAT` into `f32` and `INTEGER` into `i32`.

I think the first solution would be the correct one as it will allow to display of the correct data type in Netron, but this requires modifying all the `NNCFGraphEdge` instantiations. Or maybe I could set the parameter as optional.

Let me know your thoughts on this, so I can proceed with the implementation

**Comment by DaniAffCH** [comment]
I've just submitted the PR #2567 solving this issue

**Comment by andrey-churkin** [comment]
@DaniAffCH Thanks for the contribution!
