### ISSUE TITLE
Why the actual pruning rate of filters is not what I set?

### ISSUE THREAD

**Issue by SpongeBob-222** [openvinotoolkit/nncf#269]
Hi, I found that the actual pruning rate of filters is not what I set. 

For example, there is a layer with a total of 64 filters. I set the pruning rate to 0.3. In theory, 19 filters (round(0.3*64)=19) should be clipped, but in fact only 16 filters are clipped. 

I explored the source code , and I found that NNCF has an algorithm to calculate the actual pruning rate，the code is as follows：
![image](https://user-images.githubusercontent.com/11664658/98888960-f4482400-24d3-11eb-89b3-3dbafe38bdf2.png)

So, there are two questions that confuse me:

1. Why the actual pruning rate is not just round(pruning_rate*filters_number)?

2. Why the default number of remaining filters after filter pruning is a multiple of 8? 

Thanks!

**Comment by AlexKoff88** [comment]
Hi @SpongeBob-222,

The reason why the number of remaining filters should be multiple of 8 is caused by the specific computation of Convolution operation on CPU and GPU using SIMD or SIMT instructions. Using an arbitrary value just makes these computations inefficient because the rest of the filters (num_of_filters % 8) will be padded to 8 by zeros. So it is reasonable to make the number of filters multiple of 8 and learn something valuable.

**Comment by AlexKoff88** [comment]
BTW, we are not revising our approach to the selection of pruning filters. We are going to consider connections between the layers during filter selection and not do this post-factum when we already set them to zero and are going to remove from the network during the export to ONNX. Please find the dedicated [PR](https://github.com/openvinotoolkit/nncf/pull/256).

**Comment by SpongeBob-222** [comment]
Thank you very much!  👍: ) @AlexKoff88
