### ISSUE TITLE
Replace NMS GPU kernel in object detection sample with torchvision's implementation

### ISSUE THREAD

**Issue by vanyalzr** [openvinotoolkit/nncf#276]
Make sure that inference speed in eval mode and accuracy is not significantly affected.

In case torchvision's NMS impl is slower, clean up the existing GPU kernel by removing the empty wrapper in `nms.cpp`

**Comment by vanyalzr** [comment]
cc @ljaljushkin

**Comment by SKholkin** [comment]
There is no such big difference in both inference speed and accuracy
Actually PyTorch impl even a little bit faster and more accurate:
ssd300
PyTorch impl:
Averaged detect for batch: 1.163s
Mean AP = 0.7831
Old FB kernels:
Averaged detect for batch: 1.192s
Mean AP = 0.7828

ssd512
PyTorch impl:
Averaged detect for batch: 0.819s
Mean AP = 0.8044
Old FB kernels:
Averaged detect for batch: 0.843s
Mean AP = 0.8026

**Comment by ljaljushkin** [comment]
We also need to address Alex's comment: https://github.com/openvinotoolkit/nncf/pull/275#issuecomment-728189750
@SKholkin, please export SSD to ONNX and share a screenshot of how DetectionOutput looks like

**Comment by SKholkin** [comment]
Results after VOC12 validation changes:
ssd300 FP
PyTorch impl:
Mean AP = 0.9663
Old FB kernels:
Mean AP = 0.9653
ssd300 int8:
PyTorch impl:
Mean AP = 0.9654
Old FB kernels:
Mean AP = 0.9643
So PyTorch mAP is slightly higher than old FB's.

**Comment by SKholkin** [comment]
Various top_k validation results:
no top_k crop:
PyTorch impl:
ssd300 FP: 0.9663
ssd300 int8: 0.9654
top_k=200
PyTorch impl:
ssd300 FP: 0.9663
ssd300 int8: 0.9654
Old Fb kernels:
ssd300 FP: 0.9653
ssd300 int8: 0.9643
top_k=50
PyTorch impl:
ssd300 FP: 0.9658
ssd300 int8: 0.9649
Old Fb kernels:
ssd300 FP: 0.9522
ssd300 int8: 0.9511
top_k=20
PyTorch impl:
ssd300 FP: 0.9629
ssd300 int8: 0.9618
Old Fb kernels:
ssd300 FP: 0.9191
ssd300 int8: 0.9187
top_k=10
PyTorch impl:
ssd300 FP: 0.9542
ssd300 int8: 0.954
Old Fb kernels:
ssd300 FP: 0.871
ssd300 int8: 0.8698

**Comment by SKholkin** [comment]
As you can see on lower top_k parameter values PyTorch nms doesn't drop accuracy so much, but Old FB kernels drop a lot
So functions have different behavior at lower top_k. Though PyTorch nms implementation is a lot better.

**Comment by ljaljushkin** [comment]
Source code is available. 
* torchvision kernel - https://raw.githubusercontent.com/pytorch/vision/master/torchvision/csrc/cuda/nms_kernel.cu
* our kernel - https://raw.githubusercontent.com/openvinotoolkit/nncf/develop/examples/object_detection/layers/extensions/nms/nms_kernel.cu

I've performed a quick comparison. 
Almost all mismatches should be minor: torchvision code has more asserts, it uses templates instead of a single float type, some variables are called different. 

There're only 3 functional differences. 

```
   T Sa = (a[2] - a[0]) * (a[3] - a[1]);
   T Sb = (b[2] - b[0]) * (b[3] - b[1]);

  float Sa = (a[2] - a[0] + 1) * (a[3] - a[1] + 1);
  float Sb = (b[2] - b[0] + 1) * (b[3] - b[1] + 1);
```
```
  if (row_start > col_start)
    return;

 // if (row_start > col_start) return;
```

```
__shared__ float block_boxes[threadsPerBlock * 5];
__shared__ T block_boxes[threadsPerBlock * 4];
```

@SKholkinm could you try to align our implementation in these 3 places and compare mAP for low top_k param?

**Comment by ljaljushkin** [comment]
Custom NMS CUDA kernel from our extension uses top-k to cut a number of predictions.
It's aligned with implementation from OpenVINO: https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/mkldnn_plugin/nodes/detectionoutput.cpp#L568

NMS from Torchvision doesn't do that, and it seems we can't cut a number of detections before and after function to make results equivalent to the NMS from our extension because the top-k is used internally on par with a full array of predictions.

```    
int boxes_num = std::min(boxes.size(0), top_k);
scalar_t* boxes_dev = boxes_sorted.data<scalar_t>();
nms_kernel<<<blocks, threads>>>(boxes_num,
                                nms_overlap_thresh,
                                boxes_dev,
```

Without the top-k parameter, the implementations are equivalent, so I believe it's OK to keep the custom NMS GPU kernel.

@vanyalzr, please re-open the issue, if you don't agree or have other ideas to discuss.
