### ISSUE TITLE
[Good First Issue][NNCF]: [TorchFX] Test MinMax algorithm

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#2872]
Greetings🐱! As a part of https://github.com/openvinotoolkit/nncf/issues/2766 TorchFX PTQ backend support, we are gladly presenting to you following issue:

Implement TemplateTestMinMaxAlgorithm  as it done for other backends(example: https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/ptq/test_min_max.py)

### Example Pull Requests

https://github.com/openvinotoolkit/nncf/pull/2856

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@daniil-lyakhov 

### Ticket

#2766

**Comment by daniil-lyakhov** [comment]
Hi @Patsnoop, do you still plan to contribute?

**Comment by Patsnoop** [comment]
Good Afternoon. Yes I do plan on working on this tomorrow and submitting this weekend.

**Comment by mlukasze** [comment]
hey @Patsnoop do you need any support here?

**Comment by rk119** [comment]
Hi, is this issue being worked on? If not, I'd like to attempt this as well :) 

Thank you.

**Comment by mlukasze** [comment]
@daniil-lyakhov please reassign

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

I hope this isn't too basic of a question, but I wanted to clarify something. In the [test_get_channel_axes_matmul_torch](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_min_max.py#L162) test in TemplateTestMinMaxAlgorithm, the doc string specifies that it is to "check MatMul quantization axes in MinMax for Torch".  The test assigns layer attributes for the matmul node but I'm not sure why, when I inspected the [torch](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/model_graph_manager.py#L342) and [torch_fx](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/torch_fx_backend.py#L147) MinMax algo code, the layer_attributes aren't really used, I even commened out the [line of code](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_min_max.py#L167) and the tests still pass for both backends, is it safe to say that matmul layer attributes aren't necessary to be defined for Torch and Torch FX and that [line of code](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_min_max.py#L167) can be removed from the template since only the node metatype is utilized or what exactly would you suggest?

**Comment by daniil-lyakhov** [comment]
Hi @rk119,

Thank you for your observations! Please remove all the unused code and structures from the torch and torchFX test Min Max. And don't hesitate to open PRs and discuss ideas explicitly in the code

**Comment by rk119** [comment]
@daniil-lyakhov Alright, will do so! :) I will open a PR soon for this issue.

**Comment by alexsu52** [comment]
Thanks for the contribution!
