### ISSUE TITLE
[Good First Issue][NNCF]: [TorchFX] Test PTQ quantizer config

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#2874]
Greetings🐱! As a part of https://github.com/openvinotoolkit/nncf/issues/2766 TorchFX PTQ backend support, we are gladly presenting to you following issue:

Implement TemplateTestQuantizerConfig  as it done for other backends(example: https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/ptq/test_quantizer_config.py)

### Example Pull Requests

https://github.com/openvinotoolkit/nncf/pull/2856

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@daniil-lyakhov 

### Ticket
#2766

**Comment by anzr299** [comment]
@rk119

**Comment by rk119** [comment]
.take

**Comment by rk119** [comment]
Hi @daniil-lyakhov, 

I am encountering an issue with the `test_depthwise_conv_default_quantizer_config` test case in [test_quantizer_config.py.](https://github.com/openvinotoolkit/nncf/blob/develop/tests/post_training/test_templates/test_quantizer_config.py#L224) The test is failing because the length of `q_setup` is 1 instead of the expected 2.

Upon further investigation, I found that the [get_weight_nodes](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/torch_fx_backend.py#L348) function for Torch FX min_max does not include the `PTDepthwiseConv2dSubtype` metatype in its list of recognized metatypes. As a result, the weight nodes variable in [_get_quantizer_setup](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/algorithm.py#L569) is empty, leading to the failure.

Could you please confirm if the `PTDepthwiseConv2dSubtype` metatype should be included in the list? If so, that should resolve the issue. Else, I'd appreciate some guidance.

**Comment by daniil-lyakhov** [comment]
> Hi @daniil-lyakhov,
> 
> I am encountering an issue with the `test_depthwise_conv_default_quantizer_config` test case in [test_quantizer_config.py.](https://github.com/openvinotoolkit/nncf/blob/develop/tests/post_training/test_templates/test_quantizer_config.py#L224) The test is failing because the length of `q_setup` is 1 instead of the expected 2.
> 
> Upon further investigation, I found that the [get_weight_nodes](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/torch_fx_backend.py#L348) function for Torch FX min_max does not include the `PTDepthwiseConv2dSubtype` metatype in its list of recognized metatypes. As a result, the weight nodes variable in [_get_quantizer_setup](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/algorithm.py#L569) is empty, leading to the failure.
> 
> Could you please confirm if the `PTDepthwiseConv2dSubtype` metatype should be included in the list? If so, that should resolve the issue. Else, I'd appreciate some guidance.

Hi @rk119,
Thank you for your investigation! You are right, I've forgot to include all metatypes for nodes with weights, good catch! Please replace [current weighted metatypes list](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/torch_fx_backend.py#L351) with this [list](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/graph/operator_metatypes.py#L1113)

Thanks a lot!

**Comment by rk119** [comment]
> Hi, @rk119 , do you still plan to contribute?

Hi @daniil-lyakhov, yes I do, I'll be opening a PR for this issue by next week. I'm just a little busy with other commitments.

**Comment by alexsu52** [comment]
@rk119, thanks for the contribution!
