### ISSUE TITLE
[Good First Issue][NNCF][FBC/BC] Add a case with depthwise/transpose convolutions to the template test

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#2916]
Greetings🐱! As a part of https://github.com/openvinotoolkit/nncf/issues/2766 TorchFX PTQ backend support, we are gladly presenting to you following issue:

Turns out transposed/depthwise convolutions aren't checked by the template test. The task is to add a case with depthwise/transpose convolutions to the template test (https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_bias_correction.py#L127-L153).

### Example Pull Requests
https://github.com/openvinotoolkit/nncf/pull/2856

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@daniil-lyakhov 

### Ticket

#2766

**Comment by anzr299** [comment]
@rk119

**Comment by rk119** [comment]
.take

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

I am encountering an issue [test_update_bias](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_bias_correction.py#L144) in [TemplateTestBCAlgorithm](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_bias_correction.py), especially in this [line of code](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_bias_correction.py#L153):

 ```
 self.check_bias(quantized_model, mapped_ref_biases)
 ```
 ---
 
 I included two simple Transpose and Depthwise conv models in [helpers.py](https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/helpers.py) and here are their NNCF Graphs:
 
 #### Depthwise Convolution Test Model
 
 ```
 class DepthwiseConvTestModel(nn.Module):
    INPUT_SIZE = [1, 3, 4, 4]

    def __init__(self):
        super().__init__()
        with set_torch_seed():
            self.conv = create_depthwise_conv(3, 1, 1, 1)
            self.conv.weight.data = torch.randn([3, 1, 1, 1])
            self.conv.bias.data = torch.randn([3])

    def forward(self, x):
        return self.conv(x)
        
```
  
![image](https://github.com/user-attachments/assets/e3af87a1-a756-4790-9341-c587c9973f38)

 #### Transpose Convolution Test Model
 
 ```
 class TransposeConvTestModel(nn.Module):
    INPUT_SIZE = [1, 1, 3, 3]

    def __init__(self):
        super().__init__()
        with set_torch_seed():
            self.conv = create_transpose_conv(1, 2, 2, 1, 1, 2)
            self.conv.weight.data = torch.randn([1, 2, 2, 2])
            self.conv.bias.data = torch.randn([2])
            
    def forward(self, x):
        return self.conv(x)
        
 ```
![image](https://github.com/user-attachments/assets/1d66d991-0ad5-41d2-a7ce-12cc9d109b9e)

---

I am encountering an issue in [check_bias ](https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/fx/test_bias_correction.py#L76-L83) function for Torch FX backend, specifically in the function [get_bias_value](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/experimental/torch/fx/node_utils.py#L76-L88) in the `/nncf/experimental/torch/fx/node_utils.py` file. Here the Depthwise Conv test passes since this function accesses the `add_tensor` node which has the bias value as the second input. However, I am struggling to access the bias value in Transpose Conv as it is the third input within the `conv_transpose2d` node itself.

Do you have any suggestions regarding this? I'd appreciate your guidance.

Thanks.

**Comment by daniil-lyakhov** [comment]
Hello, @rk119,
Thank you for your analysis! Regarding TorchFX: nncf_graphs passed to the Bias Correction algo should always have a bias node as a separate node in NNCFGraph and not as a third argument of the convolution. To archive that, this [transformation](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/experimental/torch/fx/quantization/quantize_model.py#L87) is being used in MinMax (and is duplicated [here](https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/fx/test_bias_correction.py#L44) in BC tests). Looks like transpose convolutions have different types, please check it out and make sure test NNCFGraph has indeed a separate bias node.

Regarding other backends: could you please clarify, what bias isn't applied mean in this context?

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

Here is an update. Yes, the problem was in `nncf/experimental/torch/fx/transformations.py` specifically [here](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/experimental/torch/fx/transformations.py#L565). The function was not accounting for the target of the `conv_transpose2d` node. After exploring the FX graph, I obtained the following information for the `conv_transpose2d` node:

![image](https://github.com/user-attachments/assets/5f7906b9-42a7-47ab-beda-12ec8b3ce71f)

I modified the [function](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/experimental/torch/fx/transformations.py#L565) and included the target. Confirmed the structure of the NNCF graph for the Transpose Convolution Test Model:

![image](https://github.com/user-attachments/assets/cf074f2e-3f9a-403c-898c-c4c52a5c306b)

It was as expected. Furthermore, the tests passed for Torch FX!

I am still exploring the other backends and will update you with the exact information regarding my errors.

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

I found the issue with onnx backend. The test was failing because [get_bias_tensor_port_id](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/onnx/graph/nncf_graph_builder.py#L103-L112) was returning `None` since the [OPERATIONS_WITH_BIAS ](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/onnx/graph/metatypes/groups.py#L145) list did not have the metatype [onnx_metatypes.ONNXConvolutionTransposeMetatype](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/onnx/graph/metatypes/onnx_metatypes.py#L118). Once I added it into the [list](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/onnx/graph/metatypes/groups.py#L145), the tests were passing for ONNX backend. 

I hope this is alright?

**Comment by daniil-lyakhov** [comment]
Hi @rk119,
Please add missing metatypes in ONNX and update the `map_reference` method in OV backend. You can use `model_cls` parameter to distinguish between the transpose conv model and the other models.

**Comment by rk119** [comment]
> You can use `model_cls` parameter to distinguish between the transpose conv model and the other models.

Hi @daniil-lyakhov, 

Alright, I was planning on doing that. Thank you for your suggestions!

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

The digits dynamically change after the underscore in `ConvolutionBackpropData_13554` in the NNCF graph when I run the test multiple times, this seems to make it difficult to map the bias to the corresponding node in in this [function](https://github.com/openvinotoolkit/nncf/blob/develop/tests/openvino/native/test_bias_correction.py#L60-L62).

**Comment by daniil-lyakhov** [comment]
Hi @rk119,
Please use the same approach as torch FX: https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/fx/test_bias_correction.py#L61-L67

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

I realized the op for TransposeConvolution isn't supported in OpenVino as I have confirmed in [openvino_metatypes](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/openvino/graph/metatypes/openvino_metatypes.py) and [here](https://github.com/openvinotoolkit/openvino/tree/master/src/core/include/openvino/opsets) hence concluded that it isn't supported. The op `ConvolutionBackpropData` didn't seem right for Transpose Convolution. Furthermore, in [https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/fx/test_bias_correction.py#L59-L67](https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/fx/test_bias_correction.py#L59-L67), the Torch FX model reproduces the same node names for the convolution models, even for Multiple Convolutions, it is named incrementally hence this [algorithm ](https://github.com/openvinotoolkit/nncf/blob/develop/tests/torch/fx/test_bias_correction.py#L62-L67) makes sense and is possible. But in the openvino model the Transpose Convolution is converted into a node with type `ConvolutionBackpropData` and name `ConvolutionBackpropData_{digits}`. The digits are different (like `ConvolutionBackpropData_4` or `ConvolutionBackpropData_82673`) in multiple runs of the same test and don't seem to have a proper pattern for me to code an algorithm in [https://github.com/openvinotoolkit/nncf/blob/develop/tests/openvino/native/test_bias_correction.py#L60-L62](https://github.com/openvinotoolkit/nncf/blob/develop/tests/openvino/native/test_bias_correction.py#L60-L62). I investigated further and realized it wasn't supported. 

Will it make sense to skip testing Transpose Convolution for OpenVino backend for now and only test Transpose Convolution for FX and ONNX backends as they support the op for Transpose Convolution?

**Comment by daniil-lyakhov** [comment]
@rk119, `TransposeConvolution` is indeed called `ConvolutionBackpropData` in openvino. Please support `ConvolutionBackpropData` in openvino BC tests and just pick the name of the first convolution node in the `map_references` function

**Comment by rk119** [comment]
> @rk119, `TransposeConvolution` is indeed called `ConvolutionBackpropData` in openvino. Please support `ConvolutionBackpropData` in openvino BC tests and just pick the name of the first convolution node in the `map_references` function

Oh, I apologize for misunderstanding then. Alright then, I will create a draft PR for now :)

**Comment by alexsu52** [comment]
Thanks for your contribution!
