### ISSUE TITLE
[Good First Issue][NNCF][MinMax]: move `get_statistic_collector` to the common part

### ISSUE THREAD

**Issue by daniil-lyakhov** [openvinotoolkit/nncf#3120]
### Context

MinMax algorithm backend has the  [`get_statistic_collector`](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/backend.py#L232-L252) method. Previously, backends have different implementations and require different reducers/aggregators maps, thus this method was justified. Now all reducers and aggregators were unified, and we just have 4 identical method copies in each backend: [ONNX](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/onnx_backend.py#L177-L220), [OpenVINO](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/openvino_backend.py#L167-L210), [Torch](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/torch_backend.py#L161-L206), [TorchFX](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/torch_fx_backend.py#L153-L198). (Openvino is actually using `inplace` attribute besides other backend, but this attribute is common as well and could be passed to each backend)

### What needs to be done?

The task is to move `get_statistic_collector` implementation to the [common algorithm file](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/algorithm.py) and to adjust all the min max tests: 
* https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_min_max.py
* https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_ptq_params.py
* https://github.com/openvinotoolkit/nncf/blob/develop/tests/cross_fw/test_templates/test_quantizer_config.py

### Example Pull Requests

https://github.com/openvinotoolkit/nncf/pull/2856

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/nncf/blob/develop/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

@daniil-lyakhov

**Comment by rk119** [comment]
.take

**Comment by unKnownNG** [comment]
Can I contribute in this issue??

**Comment by AHB102** [comment]
@daniil-lyakhov Could you please tag me when the issues are created? :)

**Comment by daniil-lyakhov** [comment]
> @daniil-lyakhov Could you please tag me when the issues are created? :)

Sure!

**Comment by rk119** [comment]
Hi @daniil-lyakhov,

Before I get into it, I just want to clarify and confirm a few things. 

The reducer maps for [PT](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/tensor_statistics/collectors.py#L385-L392), [FX](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/torch/tensor_statistics/collectors.py#L385-L392) and [ONNX](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/onnx/statistics/collectors.py#L120-L127) are the same but for [OV](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/openvino/statistics/collectors.py#L154-L161) they are different as they define and utilize the `get_inplace_fn` function. I was planning on making a common reducers map [here](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/experimental/common/tensor_statistics/collectors.py#L836) since the `get_statistic_collector` function has to be moved to the common algorithm, I wanted to ask on how to approach the different reducer maps for OV vs other backends since some of the reducers [here](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/experimental/common/tensor_statistics/collectors.py#L410-L540) do not implement the `get_inplace_fn` or is there a better approach to implement it?

**Comment by daniil-lyakhov** [comment]
> planning on making a common reducers map

Hi @rk119,
I believe the best way is to create a backend property like `reducers_map` and specify the map for each backend. You can put the common non inplace reducers map to the common file [here](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/experimental/common/tensor_statistics/collectors.py) and specify the openvino-specific reducers in the [openvino backend](https://github.com/openvinotoolkit/nncf/blob/develop/nncf/quantization/algorithms/min_max/openvino_backend.py) file.
