### ISSUE TITLE
Long delay when start filter pruning for MobileNet v2

### ISSUE THREAD

**Issue by AlexKoff88** [openvinotoolkit/nncf#352]
I have a long delay between initialization and first iteration on my machine when starting the filter pruning method for MobileNet v2 model (~10-15 min). The issue is not observed for ResNet-18, for example.

Please consider with low priority.

Here is a config:
```
{
    "model": "mobilenet_v2",
    "pretrained": true,
    "batch_size" : 512,
    "epochs": 100,
    "input_info": {
      "sample_size": [1, 3, 224, 224]
    },
    "optimizer": {
        "type": "SGD",
        "base_lr": 0.1,
        "weight_decay": 1e-5,
        "schedule_type": "multistep",
        "steps": [
            20,
            40,
            60,
            80
        ],
        "optimizer_params":
        {
            "momentum": 0.9,
            "nesterov": true
        }
    },
       "compression": [
       {
        "algorithm": "filter_pruning",
	"pruning_init": 0.1,
        "params": {
	    "schedule": "exponential",
            "pruning_target": 0.3,
            "pruning_steps": 15,
            "weight_importance": "geometric_median"
        }
        }
       ]
}
```

**Comment by mkaglins** [comment]
This long delay caused by `geometric_median` weight importance function that takes a long time for layers with a lot of output channels (like in MobileNetV2).

Also was found that weight importances calculates twice because of the scheduler redundant initialization pruning rate.

In #365 scheduler was fixed and an information message about a potentially long time of norms calculation was added.
