### ISSUE TITLE
Is filter-prunning of layers with skip connections supported?

### ISSUE THREAD

**Issue by korabelnikov** [openvinotoolkit/nncf#588]
I've just started using NNCF for structured prunning of ResNet18 with help of 'geometric mean' method.
I noticed that ~50% layers is not affected by this procedure, namely those connected to residuals

I understand such optimization requires simultaneous optimization of all such layers, but do you have method to deal with it? Or do you have plan to implement it?

Thank you for your work
![image](https://user-images.githubusercontent.com/3808833/111901310-60213700-8a48-11eb-8900-b9173a59a0dd.png)

**Comment by vshampor** [comment]
@mkaglins @AlexanderDokuchaev

**Comment by AlexanderDokuchaev** [comment]
Hi @korabelnikov 

By default we don`t prune first convolution and downsample layers, as result it blocks prununing of last convolution layers in resnet blocks.
It's done because pruning of this layers effect to accuracy too much.

But if you want to prune all layers you can change config file. Set `prune_downsample_convs` and `prune_first_conv` as true. In this case all layers in ResNet will be pruned.

```json
    "compression": [
        {
            "algorithm": "filter_pruning",
            "pruning_init": 0.1,
            "params": {
                "schedule": "exponential",
                "pruning_target": 0.4,
                "prune_downsample_convs": true,
                "prune_first_conv": true,
                "pruning_steps": 15,
                "weight_importance": "geometric_median"
             }
       }
    ]

```

**Comment by vshampor** [comment]
@korabelnikov could your issue be resolved?

**Comment by korabelnikov** [comment]
Thank you for a respond, I will try `prune_downsample_convs ` right now and post results here

**Comment by korabelnikov** [comment]
![image](https://user-images.githubusercontent.com/3808833/113325881-a5cfe080-9321-11eb-86d1-34111a86f080.png)

Works for downsampled convolutions. Thank you.

As I understood, first two residual blocks can be pruned with first conv only, because they are connected through 'Add'.
Either last residual block can be pruned only with last layer (FC in my case).

**Comment by mkaglins** [comment]
@korabelnikov You are totally right about the pruning first and last residual blocks.

To prune the first two residual blocks you need to set `"prune_first_conv": true` as mentioned above. 

Unfortunately, the last residual block can't be pruned because the pruning of FC layers is not currently supported.
