### ISSUE TITLE
Setup for Test Environment

### ISSUE THREAD

**Issue by vuiseng9** [openvinotoolkit/nncf#608]
Wonder if I miss this, there is no documentation on setting up the test environment, I'm assuming ```requirements.txt``` in the ```tests``` folder is all we need. but it doesn't work out of the box for my case, so providing feedback of the steps that get it to run locally.

1. missing/outdated packages
```
onnx==1.8.1
onnxruntime==1.7.0
mlflow
returns
```
2.  protobuf compiler is required. I used conda's ```conda install -c anaconda protobuf```

**Comment by vshampor** [comment]
@vuiseng9 the mlflow and returns are specified in examples/requirements.txt instead. The onnx, onnxruntime and protobuf versions are specified in tests/requirements.txt. It seems that we specify all the required packages - also I am reluctant to relax the protobuf version because the protobuf dependency is in itself a workaround for namespace bugs. The only thing that is actionable here is perhaps changing `onnxruntime==1.6.0` to `onnxruntime>=1.6.0`, so we might do it. Perhaps I am missing something else here?

**Comment by vuiseng9** [comment]
@vshampor figured out where i missed. I started on fresh environment, i only install nncf but didn't get examples set up, so mlflow and returns were missing. However, there are tests specifically testing the samples, shouldn't examples' requirements part of tests' requirements.txt? Anyway, i guess this is a minor issue. 

As for protobuf, the package is installed via the requirements.txt but it couldn't run without a compiler executable, instead of installing via apt-get i used conda. I am not certain if this would be experienced by others, just capturing here for reference.

your suggestion of onnxruntime makes sense as different version is available per python version.
