### ISSUE TITLE
Question: how pick up pruning ratio for every layer?

### ISSUE THREAD

**Issue by korabelnikov** [openvinotoolkit/nncf#623]
As I understood, it's possible to set up individual `pruning_ratio` for every layer in filter pruning task.

It's obvious that different layers compress different.

Q: is it some heuristics exist? or can we numerically optimize these values for each layer?  What is implemented in nncf?

**Comment by vshampor** [comment]
Greetings, @korabelnikov!

Picking an individual pruning ratio for each layer is in essence a hyperparameter search. All methods for doing so are applicable in NNCF's case; NNCF should allow setting per-layer pruning rate directly in the training pipeline, so you could feasibly integrate a reinforcement learning algorithm with NNCF's pruning controller object, if you so desire, and target it for simultaneous quality metric and pruning ratio maximization. No built-in heuristic currently exists in NNCF for pruning AFAIK, but we will definitely be providing one in the future for best default experience.

**Comment by korabelnikov** [comment]
Thank you for the answer

**Comment by vanyalzr** [comment]
Hi @korabelnikov,

Please refer to [this PR](github.com/openvinotoolkit/nncf/pull/605) to see how you could manually set group-wise pruning rates for the model, we expect to merge it soon. Note that these are groups of dependent layers, not individual layers. 

As for heuristics, you can choose a uniform pruning rate across groups by setting the `all_weights` flag to False (it is False by default), otherwise a global pooling of filter importance scores would be done and a global threshold to prune filters in all layer groups would be calculated. Pruning according to the threshold results in a non-uniform pruning rate pattern. 

Finally, if you set the `prune_flops` flag to True, the least important filters would be globally pruned one-by-one until the target FLOPs are not reached, also giving a non-uniform pruning rate.
