### ISSUE TITLE
Questions about "Fixed bias pruning in depthwise convolution" in v1.7.0

### ISSUE THREAD

**Issue by zhangliliang** [openvinotoolkit/nncf#710]
In the release note of v1.7.0, it claims that "Fixed bias pruning in depthwise convolution" is a notable bugfix.

If we use an older version to train a network using depthwise conv, what is the side effect of it ? 

Recently we use nncf of v1.5.0 to quantize a network using depthwise conv. After training the model and exporting to onnx, we execute the model via onnxruntime, but find a large performance degradation when compared to the results run in pytorch with quantization.

I am curious about whether it would have some connections of this bugfix.

**Comment by vshampor** [comment]
@AlexanderDokuchaev to give more comments on bias pruning for depthwise conv, if necessary.

@zhangliliang I don't think that it is correct to compare the PyTorch inference runs of networks with NNCF-enabled quantization, and the ONNX runtime runs of the same - the ONNX runtime probably uses CPU while PyTorch uses GPU, and even if you run PyTorch in the CPU mode, then the performance may still not be aligned between the two backends due to potentially different optimizations being used.

Also the fix only pertains to the pruning algorithm usage - the existing compression training flows that only use quantization (and not pruning) should not be impacted by this fix.
